apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
    app-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:   
          - name: ADMINER_DESIGN
            value: {{ .Values.theme }}
      {{- if .Values.db.server }}            
          - name: ADMINER_DEFAULT_SERVER
            value: {{ .Values.db.server }}
      {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30   
