# global configuration
global:
  # global host name
  default_url:

# Name of the instance, default {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
name:

# Adminer image
image:
  # Docker registry
  registry: "docker.io"
  # Docker image
  repository: "adminer"
  # Docker version
  tag: 4.8.1-standalone

# service
service:
  port: 8080

# post configuration
pod:
  # pot port
  port: 8080

imagePullPolicy: IfNotPresent

# Route
routing:
  # Enable or disable route
  enabled: true

  # Default URL
  default_url: "change.com"

  # ingress
  ingress:
    # aditional annotations    
    annotations: {}
    #  traefik.ingress.kubernetes.io/router.middlewares: traefik-develop-basic-auth@kubernetescrd

# database configuration
db:
  # default server
  server:

# Replicas
replicas: 1

# Adminer theme
theme: "pepa-linha"